
services:
  app:
    build: .
    container_name: bangkah_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    networks:
      - bangkahnet

  nginx:
    image: nginx:1.25-alpine
    container_name: bangkah_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - bangkahnet



networks:
  bangkahnet:
    driver: bridge
